version: '3.8'

services:
  game:
    image: game_project_img
    build:
      context: .
      dockerfile: docker/Node_js/Dockerfile
      
    ports:
      - "3000:3000"
    command:  sh -c "npm run build && npm start"

    volumes:
      - /sgoinfre/${USER}/ft_trans/db:/app/db

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s
    container_name: game_project_cont
    user: appuser


